Repository kubesphere/devops-agent, pull requests merged in 2021-08, with the labels that each got.

#28 Add docker login and gh repo fork
  .gitpod.yml
Labels: approved, lgtm, size/XS

#29 Fix the invalid keyserver of gpg
  nodejs/Dockerfile
Labels: approved, lgtm, size/XS

#31 Add a Python Jenkins k8s agent image
  .github/workflows/build-podman.yaml
  .github/workflows/build.yaml
  python/Dockerfile
  python/Jenkinsfile
  python/podman/Dockerfile
Labels: approved, size/L

#36 Add the missing python image declaration in README
  README.md
Labels: approved, lgtm, size/XS

#33 Add editorconfig to guarantee the basic code style
  .editorconfig
Labels: approved, size/S
