Repository kubesphere/devops-agent, pull requests merged in 2021-11, with the labels that each got.

#51 Rectify suffix to -1.16 for golang16 agent
  .github/workflows/build.yaml
Labels: kind/bug, lgtm, size/S

#58 Fix dependency package problem #3
  dotnet/Dockerfile
Labels: approved, lgtm, size/S

#45 Add gradle (6.9.1) agent
  .github/workflows/build-podman.yaml
  .github/workflows/build.yaml
  README.md
  gradle/Dockerfile
  gradle/Jenkinsfile
  gradle/podman/Dockerfile
  gradle/set_java
Labels: lgtm, size/L, hacktoberfest-accepted
